### ISSUE TITLE
simple temporary page

### ISSUE THREAD

**Issue by gauteh** [astroidmail/astroidmail.github.io#1]
maybe we should have a simple page with a screenshot just redirecting to the repository for the time being. i think the non-working site is likely to make people concerned about how active the project is.

**Comment by gauteh** [comment]
@hugoroy: ping

**Comment by hugoroy** [comment]
## Totally. Sorry for this! I will take care of it soon (currently away without my laptop).

Envoyé de mon appareil mobile. 
Sent from my mobile device.

**Comment by gauteh** [comment]
Great, thanks!
