### ISSUE TITLE
Use new logo

### ISSUE THREAD

**Issue by gauteh** [astroidmail/astroidmail.github.io#3]
@mxmehl , @hugoroy maybe you want to do this?

**Comment by hugoroy** [comment]
Sure. Will do.

Le 3 mars 2017 13:35:38 GMT+01:00, Gaute Hope <notifications@github.com> a écrit :
>@mxmehl , @hugoroy maybe you want to do this?

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
